log_format: '[%(name)s][%(asctime)s][%(lineno)3d][%(levelname)7s] %(message)s'
date_time_format: '%m-%d %H:%M:%S'
log_level: 'DEBUG'


sspanel_url: 'https://panel.ss.com'
key: 'this_is_mu_key'
node_id: 14

diff_time: 10
post_load_period: 60

manager_ip: '127.0.0.1'
manager_port: 8839

fast_open: true
plugin: 'obfs-server'
plugin_opts: 'obfs=http;fast-open'
mode: 'tcp_and_udp'
